/**
 * Affiliate attribution — the two halves that were missing.
 *
 * The data model (Affiliate / AffiliateConversion / AffiliatePayout) and the
 * commission tiers already existed, but nothing connected them to reality:
 * a `?ref=` click was never remembered, and a successful payment never created
 * a conversion. An affiliate could send real customers and still see zero.
 *
 * The chain now runs:
 *
 *   1. proxy.ts sees `?ref=CODE` and drops the REF_COOKIE.
 *   2. A signup calls claimReferral() — the code is stored against the new
 *      account's email, because at signup time there is no company yet.
 *   3. The billing webhook calls recordAffiliateConversion() once payment is
 *      confirmed, resolving the claim from the company owner's email.
 *
 * Storage is an ActivityLog row rather than a new table: the same pattern the
 * comms vault and dev-test company already use, and it keeps this off the
 * critical path of a schema migration against a live database.
 */
import { prisma } from "@/lib/prisma";

/** 60 days. Long enough to cover a trial-and-think cycle, short enough to expire. */
export const REF_COOKIE = "fos_ref";
export const REF_COOKIE_MAX_AGE = 60 * 60 * 24 * 60;

const CLAIM_ACTION = "AFFILIATE_REFERRAL_CLAIM";
const CONVERSION_ACTION = "AFFILIATE_CONVERSION_RECORDED";

/** Tracking codes are generated by us; refuse anything that is not one. */
export function normalizeTrackingCode(raw: string | null | undefined): string | null {
  const code = String(raw || "").trim();
  if (!code || code.length > 64) return null;
  return /^[A-Za-z0-9_-]+$/.test(code) ? code : null;
}

/**
 * Remember that `email` arrived through `trackingCode`.
 *
 * Deliberately first-touch: if a claim already exists for this email it is left
 * alone, so a second affiliate cannot overwrite the one who actually did the
 * work by getting the customer to click a different link later.
 */
export async function claimReferral(email: string, rawCode: string | null | undefined) {
  const trackingCode = normalizeTrackingCode(rawCode);
  if (!trackingCode || !email) return null;

  const emailNormalized = email.trim().toLowerCase();

  // Unknown or unapproved affiliates are dropped here rather than at payout
  // time, so a stale link never sits in the system pretending to be worth money.
  const affiliate = await prisma.affiliate
    .findUnique({ where: { trackingCode }, select: { id: true, status: true } })
    .catch(() => null);
  if (!affiliate || affiliate.status !== "APPROVED") return null;

  const existing = await prisma.activityLog
    .findFirst({
      where: { action: CLAIM_ACTION, details: { contains: `"email":"${emailNormalized}"` } },
      select: { id: true },
    })
    .catch(() => null);
  if (existing) return null;

  await prisma.activityLog
    .create({
      data: {
        action: CLAIM_ACTION,
        details: JSON.stringify({ email: emailNormalized, trackingCode }),
      },
    })
    .catch(() => {});

  return trackingCode;
}

async function findClaimForEmail(email: string): Promise<string | null> {
  const emailNormalized = email.trim().toLowerCase();
  const row = await prisma.activityLog
    .findFirst({
      where: { action: CLAIM_ACTION, details: { contains: `"email":"${emailNormalized}"` } },
      orderBy: { createdAt: "asc" },
      select: { details: true },
    })
    .catch(() => null);
  if (!row?.details) return null;
  try {
    return normalizeTrackingCode(JSON.parse(row.details).trackingCode);
  } catch {
    return null;
  }
}

/**
 * Turn a confirmed payment into commission.
 *
 * Idempotent per company: a subscription renewal fires the same webhook every
 * cycle, and paying a commission again on each renewal would quietly multiply
 * what is owed. One conversion per referred company, on first payment.
 */
export async function recordAffiliateConversion(params: {
  companyId: string;
  customerEmail: string;
  customerName?: string | null;
  plan?: string | null;
  planAmount?: number | null;
}): Promise<{ recorded: boolean; commissionAmt?: number; reason?: string }> {
  const trackingCode = await findClaimForEmail(params.customerEmail);
  if (!trackingCode) return { recorded: false, reason: "no-claim" };

  const already = await prisma.activityLog
    .findFirst({
      where: { action: CONVERSION_ACTION, companyId: params.companyId },
      select: { id: true },
    })
    .catch(() => null);
  if (already) return { recorded: false, reason: "already-recorded" };

  const affiliate = await prisma.affiliate.findUnique({ where: { trackingCode } });
  if (!affiliate) return { recorded: false, reason: "affiliate-missing" };
  if (affiliate.status !== "APPROVED") return { recorded: false, reason: "affiliate-not-approved" };

  const planAmount = typeof params.planAmount === "number" ? params.planAmount : 0;
  const commissionAmt = parseFloat((planAmount * affiliate.commissionRate).toFixed(2));

  // Tier is driven by how many referrals are live *after* this one lands.
  const next = affiliate.activeReferrals + 1;
  const tier = next >= 50 ? "ELITE" : next >= 21 ? "PRO" : next >= 6 ? "GROWTH" : "STARTER";
  const commissionRate = next >= 50 ? 0.35 : next >= 21 ? 0.30 : next >= 6 ? 0.25 : 0.20;

  await prisma.$transaction([
    prisma.affiliateConversion.create({
      data: {
        affiliateId: affiliate.id,
        companyId: params.companyId,
        customerEmail: params.customerEmail.trim().toLowerCase(),
        customerName: params.customerName || undefined,
        plan: params.plan || undefined,
        planAmount,
        commissionAmt,
        status: "CONFIRMED",
      },
    }),
    prisma.affiliate.update({
      where: { id: affiliate.id },
      data: {
        totalReferrals: { increment: 1 },
        activeReferrals: { increment: 1 },
        totalEarned: { increment: commissionAmt },
        pendingBalance: { increment: commissionAmt },
        tier,
        commissionRate,
      },
    }),
    // The idempotency marker. Written in the same transaction as the payout
    // maths so the two can never disagree.
    prisma.activityLog.create({
      data: {
        action: CONVERSION_ACTION,
        companyId: params.companyId,
        details: JSON.stringify({ trackingCode, commissionAmt, planAmount }),
      },
    }),
  ]);

  return { recorded: true, commissionAmt };
}
