export type DashboardFeaturePlanCode = "STARTER" | "PRO" | "ENTERPRISE" | "CUSTOM";

export type DashboardBusinessGroup = "retail" | "distribution" | "trading" | "manufacturing" | "service" | "restaurant" | "healthcare" | "real_estate" | "construction" | "school" | "hotel" | "pharmacy" | "transport" | "trade" | "ecommerce" | "salon" | "gym" | "agriculture" | "ngo" | "law_firm" | "it" | "automotive" | "repair" | "maintenance" | "media" | "subscriptions" | "isp" | "solar" | "events" | "rentals" | "firm" | "franchise";

export type DashboardFeatureDefinition = {
  id: string;
  label: string;
  route: string;
  business: DashboardBusinessGroup;
  businessLabel: string;
  section: string;
  businessTypes?: string[];
  description?: string;
  category?: string;
  plans?: string[];
  defaultEnabled?: boolean;
};

export const DASHBOARD_FEATURE_DEFS: DashboardFeatureDefinition[] = [
  {
    id: "SALON_OVERVIEW",
    label: "Salon Overview",
    route: "/dashboard/salon",
    business: "salon",
    businessLabel: "Salon / Beauty",
    section: "Control Center",
    businessTypes: ["salon"],
  },
  {
    id: "SALON_APPOINTMENTS",
    label: "Appointments",
    route: "/dashboard/salon/appointments",
    business: "salon",
    businessLabel: "Salon / Beauty",
    section: "Front Desk",
    businessTypes: ["salon"],
  },
  {
    id: "SALON_STYLISTS",
    label: "Stylists",
    route: "/dashboard/salon/stylists",
    business: "salon",
    businessLabel: "Salon / Beauty",
    section: "Team & Capacity",
    businessTypes: ["salon"],
  },
  {
    id: "SALON_SERVICES",
    label: "Service Menu",
    route: "/dashboard/salon/services",
    business: "salon",
    businessLabel: "Salon / Beauty",
    section: "Commercial",
    businessTypes: ["salon"],
  },
  {
    id: "SALON_PACKAGES",
    label: "Beauty Packages",
    route: "/dashboard/salon/packages",
    business: "salon",
    businessLabel: "Salon / Beauty",
    section: "Commercial",
    businessTypes: ["salon"],
  },
  {
    id: "SALON_CLIENT_HISTORY",
    label: "Client History",
    route: "/dashboard/salon/client-history",
    business: "salon",
    businessLabel: "Salon / Beauty",
    section: "Customer Desk",
    businessTypes: ["salon"],
  },
  {
    id: "SALON_ANALYTICS",
    label: "Salon Analytics",
    route: "/dashboard/salon/analytics",
    business: "salon",
    businessLabel: "Salon / Beauty",
    section: "Control Center",
    businessTypes: ["salon"],
  },
  {
    id: "GYM_OVERVIEW",
    label: "Gym Overview",
    route: "/dashboard/gym",
    business: "gym",
    businessLabel: "Gym / Fitness",
    section: "Control Center",
    businessTypes: ["gym"],
  },
  {
    id: "GYM_MEMBERSHIPS",
    label: "Memberships",
    route: "/dashboard/gym/memberships",
    business: "gym",
    businessLabel: "Gym / Fitness",
    section: "Membership Desk",
    businessTypes: ["gym"],
  },
  {
    id: "GYM_CLASSES",
    label: "Classes",
    route: "/dashboard/gym/classes",
    business: "gym",
    businessLabel: "Gym / Fitness",
    section: "Operations",
    businessTypes: ["gym"],
  },
  {
    id: "GYM_TRAINERS",
    label: "Trainers",
    route: "/dashboard/gym/trainers",
    business: "gym",
    businessLabel: "Gym / Fitness",
    section: "Operations",
    businessTypes: ["gym"],
  },
  {
    id: "GYM_ANALYTICS",
    label: "Gym Analytics",
    route: "/dashboard/gym/analytics",
    business: "gym",
    businessLabel: "Gym / Fitness",
    section: "Control Center",
    businessTypes: ["gym"],
  },
  {
    id: "AGRICULTURE_OVERVIEW",
    label: "Farm Overview",
    route: "/dashboard/agriculture",
    business: "agriculture",
    businessLabel: "Agriculture / Farm",
    section: "Control Center",
    businessTypes: ["agriculture"],
  },
  {
    id: "AGRICULTURE_CROPS",
    label: "Crops",
    route: "/dashboard/agriculture/crops",
    business: "agriculture",
    businessLabel: "Agriculture / Farm",
    section: "Farm Desk",
    businessTypes: ["agriculture"],
  },
  {
    id: "AGRICULTURE_LIVESTOCK",
    label: "Livestock",
    route: "/dashboard/agriculture/livestock",
    business: "agriculture",
    businessLabel: "Agriculture / Farm",
    section: "Farm Desk",
    businessTypes: ["agriculture"],
  },
  {
    id: "AGRICULTURE_FIELDS",
    label: "Fields",
    route: "/dashboard/agriculture/fields",
    business: "agriculture",
    businessLabel: "Agriculture / Farm",
    section: "Farm Desk",
    businessTypes: ["agriculture"],
  },
  {
    id: "AGRICULTURE_HARVEST",
    label: "Harvest",
    route: "/dashboard/agriculture/harvest",
    business: "agriculture",
    businessLabel: "Agriculture / Farm",
    section: "Farm Desk",
    businessTypes: ["agriculture"],
  },
  {
    id: "AGRICULTURE_ANALYTICS",
    label: "Farm Analytics",
    route: "/dashboard/agriculture/analytics",
    business: "agriculture",
    businessLabel: "Agriculture / Farm",
    section: "Control Center",
    businessTypes: ["agriculture"],
  },
  {
    id: "NGO_OVERVIEW",
    label: "NGO Overview",
    route: "/dashboard/ngo",
    business: "ngo",
    businessLabel: "NGO / Non-Profit",
    section: "Control Center",
    businessTypes: ["ngo"],
  },
  {
    id: "NGO_DONORS",
    label: "Donors",
    route: "/dashboard/ngo/donors",
    business: "ngo",
    businessLabel: "NGO / Non-Profit",
    section: "Fundraising",
    businessTypes: ["ngo"],
  },
  {
    id: "NGO_GRANTS",
    label: "Grants",
    route: "/dashboard/ngo/grants",
    business: "ngo",
    businessLabel: "NGO / Non-Profit",
    section: "Fundraising",
    businessTypes: ["ngo"],
  },
  {
    id: "NGO_BENEFICIARIES",
    label: "Beneficiaries",
    route: "/dashboard/ngo/beneficiaries",
    business: "ngo",
    businessLabel: "NGO / Non-Profit",
    section: "Programs",
    businessTypes: ["ngo"],
  },
  {
    id: "NGO_FUNDS",
    label: "Fund Accounting",
    route: "/dashboard/ngo/funds",
    business: "ngo",
    businessLabel: "NGO / Non-Profit",
    section: "Finance Desk",
    businessTypes: ["ngo"],
  },
  {
    id: "NGO_ANALYTICS",
    label: "NGO Analytics",
    route: "/dashboard/ngo/analytics",
    business: "ngo",
    businessLabel: "NGO / Non-Profit",
    section: "Control Center",
    businessTypes: ["ngo"],
  },
  {
    id: "LAW_OVERVIEW",
    label: "Law Overview",
    route: "/dashboard/law-firm",
    business: "law_firm",
    businessLabel: "Law Firm",
    section: "Control Center",
    businessTypes: ["law_firm"],
  },
  {
    id: "LAW_CASES",
    label: "Cases",
    route: "/dashboard/law-firm/cases",
    business: "law_firm",
    businessLabel: "Law Firm",
    section: "Practice Desk",
    businessTypes: ["law_firm"],
  },
  {
    id: "LAW_CLIENTS",
    label: "Clients",
    route: "/dashboard/law-firm/clients",
    business: "law_firm",
    businessLabel: "Law Firm",
    section: "Practice Desk",
    businessTypes: ["law_firm"],
  },
  {
    id: "LAW_BILLING",
    label: "Legal Billing",
    route: "/dashboard/law-firm/billing",
    business: "law_firm",
    businessLabel: "Law Firm",
    section: "Finance Desk",
    businessTypes: ["law_firm"],
  },
  {
    id: "LAW_TIME_BILLING",
    label: "Time Billing",
    route: "/dashboard/law-firm/time-billing",
    business: "law_firm",
    businessLabel: "Law Firm",
    section: "Finance Desk",
    businessTypes: ["law_firm"],
  },
  {
    id: "LAW_ANALYTICS",
    label: "Law Analytics",
    route: "/dashboard/law-firm/analytics",
    business: "law_firm",
    businessLabel: "Law Firm",
    section: "Control Center",
    businessTypes: ["law_firm"],
  },
  {
    id: "IT_OVERVIEW",
    label: "IT Overview",
    route: "/dashboard/it",
    business: "it",
    businessLabel: "IT Company",
    section: "Control Center",
    description: "IT project, contract, sprint, aur support command center.",
    category: "business_modules",
    businessTypes: ["it_company"],
    plans: ["starter", "professional", "enterprise"],
    defaultEnabled: true,
  },
  {
    id: "IT_PROJECTS",
    label: "Projects",
    route: "/dashboard/it/projects",
    business: "it",
    businessLabel: "IT Company",
    section: "Delivery",
    businessTypes: ["it_company", "consultancy_firm", "architecture_firm"],
  },
  {
    id: "IT_SPRINTS",
    label: "Sprints",
    route: "/dashboard/it/sprints",
    business: "it",
    businessLabel: "IT Company",
    section: "Delivery",
    businessTypes: ["it_company"],
  },
  {
    id: "IT_CONTRACTS",
    label: "Contracts",
    route: "/dashboard/it/contracts",
    business: "it",
    businessLabel: "IT Company",
    section: "Commercial",
    businessTypes: ["it_company"],
  },
  {
    id: "IT_ANALYTICS",
    label: "IT Analytics",
    route: "/dashboard/it/analytics",
    business: "it",
    businessLabel: "IT Company",
    section: "Control Center",
    description: "Delivery health, support backlog, aur stack mix analytics.",
    category: "business_modules",
    businessTypes: ["it_company"],
    plans: ["starter", "professional", "enterprise"],
    defaultEnabled: true,
  },
  {
    id: "IT_SUPPORT",
    label: "Support Tickets",
    route: "/dashboard/it/support",
    business: "it",
    businessLabel: "IT Company",
    section: "Support",
    businessTypes: ["it_company"],
  },
  {
    id: "AUTOMOTIVE_OVERVIEW",
    label: "Showroom Overview",
    route: "/dashboard/automotive",
    business: "automotive",
    businessLabel: "Car Showroom",
    section: "Control Center",
    businessTypes: ["car_showroom"],
  },
  {
    id: "AUTOMOTIVE_VEHICLES",
    label: "Vehicle Stock",
    route: "/dashboard/automotive/vehicles",
    business: "automotive",
    businessLabel: "Car Showroom",
    section: "Inventory",
    businessTypes: ["car_showroom"],
  },
  {
    id: "AUTOMOTIVE_TEST_DRIVES",
    label: "Test Drives",
    route: "/dashboard/automotive/test-drives",
    business: "automotive",
    businessLabel: "Car Showroom",
    section: "Sales Desk",
    businessTypes: ["car_showroom"],
  },
  {
    id: "AUTOMOTIVE_ANALYTICS",
    label: "Showroom Analytics",
    route: "/dashboard/automotive/analytics",
    business: "automotive",
    businessLabel: "Car Showroom",
    section: "Control Center",
    businessTypes: ["car_showroom"],
  },
  {
    id: "AUTOMOTIVE_DEALS",
    label: "Deals & Finance",
    route: "/dashboard/automotive/deals",
    business: "automotive",
    businessLabel: "Car Showroom",
    section: "Sales Desk",
    businessTypes: ["car_showroom"],
  },
  {
    id: "WORKSHOP_OVERVIEW",
    label: "Workshop Overview",
    route: "/dashboard/workshop",
    business: "automotive",
    businessLabel: "Car Workshop",
    section: "Control Center",
    businessTypes: ["car_workshop"],
  },
  {
    id: "WORKSHOP_JOBS",
    label: "Job Cards",
    route: "/dashboard/workshop/jobs",
    business: "automotive",
    businessLabel: "Workshop / Jobs",
    section: "Service Desk",
    businessTypes: ["car_workshop"],
  },
  {
    id: "WORKSHOP_PARTS",
    label: "Parts Used",
    route: "/dashboard/workshop/parts",
    business: "automotive",
    businessLabel: "Workshop / Jobs",
    section: "Service Desk",
    businessTypes: ["car_workshop"],
  },
  {
    id: "WORKSHOP_MECHANICS",
    label: "Mechanics",
    route: "/dashboard/workshop/mechanics",
    business: "automotive",
    businessLabel: "Workshop / Jobs",
    section: "Service Desk",
    businessTypes: ["car_workshop"],
  },
  {
    id: "WORKSHOP_WARRANTY",
    label: "Warranty",
    route: "/dashboard/workshop/warranty",
    business: "automotive",
    businessLabel: "Workshop / Jobs",
    section: "Service Desk",
    businessTypes: ["car_workshop"],
  },
  {
    id: "WORKSHOP_ANALYTICS",
    label: "Workshop Analytics",
    route: "/dashboard/workshop/analytics",
    business: "automotive",
    businessLabel: "Car Workshop",
    section: "Control Center",
    businessTypes: ["car_workshop"],
  },
  {
    id: "REPAIR_OVERVIEW",
    label: "Repair Overview",
    route: "/dashboard/repair",
    business: "repair",
    businessLabel: "Repair Jobs",
    section: "Control Center",
    businessTypes: ["mobile_repair", "computer_repair", "electronics_repair", "spare_parts"],
  },
  {
    id: "REPAIR_JOBS",
    label: "Repair Job Cards",
    route: "/dashboard/repair/jobs",
    business: "repair",
    businessLabel: "Repair Jobs",
    section: "Service Desk",
    businessTypes: ["mobile_repair", "computer_repair", "electronics_repair"],
  },
  {
    id: "REPAIR_PARTS",
    label: "Spare Parts",
    route: "/dashboard/repair/parts",
    business: "repair",
    businessLabel: "Repair Jobs",
    section: "Service Desk",
    businessTypes: ["mobile_repair", "computer_repair", "electronics_repair"],
  },
  {
    id: "REPAIR_WARRANTY",
    label: "Warranty",
    route: "/dashboard/repair/warranty",
    business: "repair",
    businessLabel: "Repair Jobs",
    section: "Service Desk",
    businessTypes: ["mobile_repair", "computer_repair", "electronics_repair"],
  },
  {
    id: "REPAIR_TECHNICIANS",
    label: "Technicians",
    route: "/dashboard/repair/technicians",
    business: "repair",
    businessLabel: "Repair Jobs",
    section: "Service Desk",
    businessTypes: ["mobile_repair", "computer_repair", "electronics_repair"],
  },
  {
    id: "REPAIR_ANALYTICS",
    label: "Repair Analytics",
    route: "/dashboard/repair/analytics",
    business: "repair",
    businessLabel: "Repair Jobs",
    section: "Control Center",
    businessTypes: ["mobile_repair", "computer_repair", "electronics_repair", "spare_parts"],
  },
  {
    id: "MAINTENANCE_OVERVIEW",
    label: "Maintenance Overview",
    route: "/dashboard/maintenance",
    business: "maintenance",
    businessLabel: "Equipment Maintenance",
    section: "Control Center",
    businessTypes: ["equipment_maintenance"],
  },
  {
    id: "MAINTENANCE_CONTRACTS",
    label: "AMC Contracts",
    route: "/dashboard/maintenance/contracts",
    business: "maintenance",
    businessLabel: "Equipment Maintenance",
    section: "Contracts",
    businessTypes: ["equipment_maintenance"],
  },
  {
    id: "MAINTENANCE_SCHEDULE",
    label: "Service Schedule",
    route: "/dashboard/maintenance/schedule",
    business: "maintenance",
    businessLabel: "Equipment Maintenance",
    section: "Operations",
    businessTypes: ["equipment_maintenance"],
  },
  {
    id: "MAINTENANCE_JOBS",
    label: "Service Jobs",
    route: "/dashboard/maintenance/jobs",
    business: "maintenance",
    businessLabel: "Equipment Maintenance",
    section: "Operations",
    businessTypes: ["equipment_maintenance"],
  },
  {
    id: "MAINTENANCE_PARTS",
    label: "Parts & Stock",
    route: "/dashboard/maintenance/parts",
    business: "maintenance",
    businessLabel: "Equipment Maintenance",
    section: "Operations",
    businessTypes: ["equipment_maintenance"],
  },
  {
    id: "MAINTENANCE_ANALYTICS",
    label: "Maintenance Analytics",
    route: "/dashboard/maintenance/analytics",
    business: "maintenance",
    businessLabel: "Equipment Maintenance",
    section: "Control Center",
    businessTypes: ["equipment_maintenance"],
  },
  {
    id: "MEDIA_OVERVIEW",
    label: "Media Overview",
    route: "/dashboard/media",
    business: "media",
    businessLabel: "Media & Advertising",
    section: "Control Center",
    businessTypes: ["advertising_agency", "digital_marketing", "media_house", "production_house", "printing_press"],
  },
  {
    id: "MEDIA_CAMPAIGNS",
    label: "Campaigns",
    route: "/dashboard/media/campaigns",
    business: "media",
    businessLabel: "Media & Advertising",
    section: "Campaign Desk",
    businessTypes: ["advertising_agency", "digital_marketing", "media_house", "production_house"],
  },
  {
    id: "MEDIA_CLIENTS",
    label: "Clients",
    route: "/dashboard/media/clients",
    business: "media",
    businessLabel: "Media & Advertising",
    section: "Campaign Desk",
    businessTypes: ["advertising_agency", "digital_marketing", "media_house", "production_house"],
  },
  {
    id: "MEDIA_PLAN",
    label: "Media Plan",
    route: "/dashboard/media/media-plan",
    business: "media",
    businessLabel: "Media & Advertising",
    section: "Campaign Desk",
    businessTypes: ["advertising_agency", "digital_marketing", "media_house", "production_house"],
  },
  {
    id: "MEDIA_ANALYTICS",
    label: "Media Analytics",
    route: "/dashboard/media/analytics",
    business: "media",
    businessLabel: "Media & Advertising",
    section: "Control Center",
    businessTypes: ["advertising_agency", "digital_marketing", "media_house", "production_house", "printing_press"],
  },
  {
    id: "SUBSCRIPTIONS_OVERVIEW",
    label: "SaaS Overview",
    route: "/dashboard/subscriptions",
    business: "subscriptions",
    businessLabel: "Subscriptions",
    section: "Control Center",
    businessTypes: ["saas_company", "membership_website", "subscription_box"],
  },
  {
    id: "SUBSCRIPTIONS_PLANS",
    label: "Plans",
    route: "/dashboard/subscriptions/plans",
    business: "subscriptions",
    businessLabel: "Subscriptions",
    section: "Commercial",
    businessTypes: ["saas_company", "membership_website", "subscription_box"],
  },
  {
    id: "SUBSCRIPTIONS_SUBSCRIBERS",
    label: "Subscribers",
    route: "/dashboard/subscriptions/subscribers",
    business: "subscriptions",
    businessLabel: "Subscriptions",
    section: "Customer Desk",
    businessTypes: ["saas_company", "membership_website", "subscription_box"],
  },
  {
    id: "SUBSCRIPTIONS_BILLING",
    label: "Recurring Billing",
    route: "/dashboard/subscriptions/billing",
    business: "subscriptions",
    businessLabel: "Subscriptions",
    section: "Finance Desk",
    businessTypes: ["saas_company", "membership_website", "subscription_box"],
  },
  {
    id: "SUBSCRIPTIONS_MRR",
    label: "MRR / ARR",
    route: "/dashboard/subscriptions/mrr",
    business: "subscriptions",
    businessLabel: "Subscriptions",
    section: "Control Center",
    businessTypes: ["saas_company", "membership_website", "subscription_box"],
  },
  {
    id: "MEMBERSHIP_CONTENT_TIERS",
    label: "Content Tiers",
    route: "/dashboard/subscriptions/content-tiers",
    business: "subscriptions",
    businessLabel: "Membership Website",
    section: "Content Desk",
    businessTypes: ["membership_website"],
  },
  {
    id: "MEMBERSHIP_MEMBER_ACCESS",
    label: "Member Access",
    route: "/dashboard/subscriptions/member-access",
    business: "subscriptions",
    businessLabel: "Membership Website",
    section: "Content Desk",
    businessTypes: ["membership_website"],
  },
  {
    id: "BOX_CATALOG",
    label: "Box Catalog",
    route: "/dashboard/subscriptions/box-catalog",
    business: "subscriptions",
    businessLabel: "Subscription Box",
    section: "Catalog Desk",
    businessTypes: ["subscription_box"],
  },
  {
    id: "BOX_FULFILLMENT",
    label: "Fulfillment Cycles",
    route: "/dashboard/subscriptions/fulfillment",
    business: "subscriptions",
    businessLabel: "Subscription Box",
    section: "Operations",
    businessTypes: ["subscription_box"],
  },
  {
    id: "ISP_OVERVIEW",
    label: "ISP Overview",
    route: "/dashboard/isp",
    business: "isp",
    businessLabel: "ISP / Cable Network",
    section: "Control Center",
    businessTypes: ["isp", "cable_network"],
  },
  {
    id: "ISP_CONNECTIONS",
    label: "Connections",
    route: "/dashboard/isp/connections",
    business: "isp",
    businessLabel: "ISP / Cable Network",
    section: "Operations",
    businessTypes: ["isp", "cable_network"],
  },
  {
    id: "ISP_BILLING",
    label: "Monthly Bills",
    route: "/dashboard/isp/billing",
    business: "isp",
    businessLabel: "ISP / Cable Network",
    section: "Finance Desk",
    businessTypes: ["isp", "cable_network"],
  },
  {
    id: "ISP_PACKAGES",
    label: "Packages",
    route: "/dashboard/isp/packages",
    business: "isp",
    businessLabel: "ISP / Cable Network",
    section: "Commercial",
    businessTypes: ["isp", "cable_network"],
  },
  {
    id: "ISP_SUPPORT",
    label: "Support Tickets",
    route: "/dashboard/isp/support",
    business: "isp",
    businessLabel: "ISP / Cable Network",
    section: "Support",
    businessTypes: ["isp", "cable_network"],
  },
  {
    id: "UTILITIES_OVERVIEW",
    label: "Utilities Overview",
    route: "/dashboard/utilities",
    business: "solar",
    businessLabel: "Utilities",
    section: "Control Center",
    businessTypes: ["electric_company", "gas_distribution", "water_supply"],
  },
  {
    id: "UTILITIES_CONNECTIONS",
    label: "Connections",
    route: "/dashboard/utilities/connections",
    business: "solar",
    businessLabel: "Utilities",
    section: "Operations",
    businessTypes: ["electric_company", "gas_distribution", "water_supply"],
  },
  {
    id: "UTILITIES_BILLING",
    label: "Utility Billing",
    route: "/dashboard/utilities/billing",
    business: "solar",
    businessLabel: "Utilities",
    section: "Finance Desk",
    businessTypes: ["electric_company", "gas_distribution", "water_supply"],
  },
  {
    id: "UTILITIES_METERS",
    label: "Meter Readings",
    route: "/dashboard/utilities/meters",
    business: "solar",
    businessLabel: "Utilities",
    section: "Operations",
    businessTypes: ["electric_company", "gas_distribution", "water_supply"],
  },
  {
    id: "UTILITIES_ANALYTICS",
    label: "Utilities Analytics",
    route: "/dashboard/utilities/analytics",
    business: "solar",
    businessLabel: "Utilities",
    section: "Control Center",
    businessTypes: ["electric_company", "gas_distribution", "water_supply"],
  },
  {
    id: "SOLAR_OVERVIEW",
    label: "Solar Overview",
    route: "/dashboard/solar",
    business: "solar",
    businessLabel: "Solar Company",
    section: "Control Center",
    businessTypes: ["solar_company"],
  },
  {
    id: "SOLAR_PROJECTS",
    label: "Projects",
    route: "/dashboard/solar/projects",
    business: "solar",
    businessLabel: "Solar Company",
    section: "Execution",
    businessTypes: ["solar_company"],
  },
  {
    id: "SOLAR_EQUIPMENT",
    label: "Equipment Stock",
    route: "/dashboard/solar/equipment",
    business: "solar",
    businessLabel: "Solar Company",
    section: "Execution",
    businessTypes: ["solar_company"],
  },
  {
    id: "SOLAR_AMC",
    label: "AMC Schedule",
    route: "/dashboard/solar/amc",
    business: "solar",
    businessLabel: "Solar Company",
    section: "Service Desk",
    businessTypes: ["solar_company"],
  },
  {
    id: "SOLAR_ANALYTICS",
    label: "Solar Analytics",
    route: "/dashboard/solar/analytics",
    business: "solar",
    businessLabel: "Solar Company",
    section: "Control Center",
    businessTypes: ["solar_company"],
  },
  {
    id: "EVENTS_OVERVIEW",
    label: "Events Overview",
    route: "/dashboard/events",
    business: "events",
    businessLabel: "Event Management",
    section: "Control Center",
    businessTypes: ["event_planner", "wedding_planner", "decorator", "sound_services"],
  },
  {
    id: "EVENTS_BOOKINGS",
    label: "Bookings",
    route: "/dashboard/events/bookings",
    business: "events",
    businessLabel: "Event Management",
    section: "Execution",
    businessTypes: ["event_planner", "wedding_planner", "decorator", "sound_services"],
  },
  {
    id: "EVENTS_VENDORS",
    label: "Vendors",
    route: "/dashboard/events/vendors",
    business: "events",
    businessLabel: "Event Management",
    section: "Execution",
    businessTypes: ["event_planner", "wedding_planner", "decorator", "sound_services"],
  },
  {
    id: "EVENTS_BUDGET",
    label: "Event Budget",
    route: "/dashboard/events/budget",
    business: "events",
    businessLabel: "Event Management",
    section: "Finance Desk",
    businessTypes: ["event_planner", "wedding_planner", "decorator", "sound_services"],
  },
  {
    id: "EVENTS_ANALYTICS",
    label: "Events Analytics",
    route: "/dashboard/events/analytics",
    business: "events",
    businessLabel: "Event Management",
    section: "Control Center",
    businessTypes: ["event_planner", "wedding_planner", "decorator", "sound_services"],
  },
  {
    id: "RENTALS_OVERVIEW",
    label: "Rentals Overview",
    route: "/dashboard/rentals",
    business: "rentals",
    businessLabel: "Rentals",
    section: "Control Center",
    businessTypes: ["equipment_rental", "property_rental", "generator_rental", "car_rental"],
  },
  {
    id: "RENTALS_ITEMS",
    label: "Rental Items",
    route: "/dashboard/rentals/items",
    business: "rentals",
    businessLabel: "Rental Business",
    section: "Inventory",
    businessTypes: ["equipment_rental", "property_rental", "generator_rental"],
  },
  {
    id: "RENTALS_BOOKINGS",
    label: "Bookings",
    route: "/dashboard/rentals/bookings",
    business: "rentals",
    businessLabel: "Rental Business",
    section: "Operations",
    businessTypes: ["equipment_rental", "property_rental", "generator_rental"],
  },
  {
    id: "RENTALS_AGREEMENTS",
    label: "Agreements",
    route: "/dashboard/rentals/agreements",
    business: "rentals",
    businessLabel: "Rental Business",
    section: "Operations",
    businessTypes: ["equipment_rental", "property_rental", "generator_rental"],
  },
  {
    id: "RENTALS_MAINTENANCE",
    label: "Maintenance",
    route: "/dashboard/rentals/maintenance",
    business: "rentals",
    businessLabel: "Rental Business",
    section: "Operations",
    businessTypes: ["equipment_rental", "property_rental", "generator_rental"],
  },
  {
    id: "RENTALS_ANALYTICS",
    label: "Rentals Analytics",
    route: "/dashboard/rentals/analytics",
    business: "rentals",
    businessLabel: "Rentals",
    section: "Control Center",
    businessTypes: ["equipment_rental", "property_rental", "generator_rental", "car_rental"],
  },
  {
    id: "FRANCHISE_OVERVIEW",
    label: "Franchise Overview",
    route: "/dashboard/franchise",
    business: "franchise",
    businessLabel: "Franchise",
    section: "Control Center",
    businessTypes: ["chain_store", "franchise_brand", "franchise_restaurant"],
  },
  {
    id: "FRANCHISE_OUTLETS",
    label: "Outlets",
    route: "/dashboard/franchise/outlets",
    business: "franchise",
    businessLabel: "Franchise",
    section: "HQ Desk",
    businessTypes: ["chain_store", "franchise_brand", "franchise_restaurant"],
  },
  {
    id: "FRANCHISE_ROYALTY",
    label: "Royalty",
    route: "/dashboard/franchise/royalty",
    business: "franchise",
    businessLabel: "Franchise",
    section: "HQ Desk",
    businessTypes: ["chain_store", "franchise_brand", "franchise_restaurant"],
  },
  {
    id: "FRANCHISE_ANALYTICS",
    label: "Franchise Analytics",
    route: "/dashboard/franchise/analytics",
    business: "franchise",
    businessLabel: "Franchise",
    section: "Control Center",
    businessTypes: ["chain_store", "franchise_brand", "franchise_restaurant"],
  },
  {
    id: "FIRM_OVERVIEW",
    label: "Firm Overview",
    route: "/dashboard/firm",
    business: "firm",
    businessLabel: "Professional Firm",
    section: "Control Center",
    businessTypes: ["accounting_firm", "audit_firm", "consultancy_firm", "architecture_firm"],
  },
  {
    id: "FIRM_CLIENTS",
    label: "Clients",
    route: "/dashboard/firm/clients",
    business: "firm",
    businessLabel: "Professional Firm",
    section: "Client Desk",
    businessTypes: ["accounting_firm", "audit_firm", "consultancy_firm", "architecture_firm"],
  },
  {
    id: "FIRM_PROJECTS",
    label: "Engagements",
    route: "/dashboard/firm/projects",
    business: "firm",
    businessLabel: "Professional Firm",
    section: "Delivery",
    businessTypes: ["accounting_firm", "audit_firm", "consultancy_firm", "architecture_firm"],
  },
  {
    id: "FIRM_BILLING",
    label: "Fee Billing",
    route: "/dashboard/firm/billing",
    business: "firm",
    businessLabel: "Professional Firm",
    section: "Finance Desk",
    businessTypes: ["accounting_firm", "audit_firm", "consultancy_firm", "architecture_firm"],
  },
  {
    id: "FIRM_TIMESHEETS",
    label: "Timesheets",
    route: "/dashboard/firm/timesheets",
    business: "firm",
    businessLabel: "Professional Firm",
    section: "Delivery",
    businessTypes: ["accounting_firm", "audit_firm", "consultancy_firm", "architecture_firm"],
  },
  {
    id: "CONSULTANCY_PROPOSALS",
    label: "Proposals",
    route: "/dashboard/firm/proposals",
    business: "firm",
    businessLabel: "Consultancy Firm",
    section: "Commercial",
    businessTypes: ["consultancy_firm"],
  },
  {
    id: "CONSULTANCY_DELIVERABLES",
    label: "Deliverables",
    route: "/dashboard/firm/deliverables",
    business: "firm",
    businessLabel: "Consultancy Firm",
    section: "Delivery",
    businessTypes: ["consultancy_firm"],
  },
  {
    id: "ARCH_DESIGN_BRIEFS",
    label: "Design Briefs",
    route: "/dashboard/firm/design-briefs",
    business: "firm",
    businessLabel: "Architecture Firm",
    section: "Design Desk",
    businessTypes: ["architecture_firm"],
  },
  {
    id: "ARCH_DRAWINGS",
    label: "Drawings",
    route: "/dashboard/firm/drawings",
    business: "firm",
    businessLabel: "Architecture Firm",
    section: "Design Desk",
    businessTypes: ["architecture_firm"],
  },
  {
    id: "ARCH_MILESTONES",
    label: "Milestones",
    route: "/dashboard/firm/milestones",
    business: "firm",
    businessLabel: "Architecture Firm",
    section: "Delivery",
    businessTypes: ["architecture_firm"],
  },
  {
    id: "AUDIT_PLANNING",
    label: "Audit Planning",
    route: "/dashboard/firm/audit-planning",
    business: "firm",
    businessLabel: "Audit Firm",
    section: "Audit Desk",
    businessTypes: ["audit_firm"],
  },
  {
    id: "AUDIT_FINDINGS",
    label: "Audit Findings",
    route: "/dashboard/firm/findings",
    business: "firm",
    businessLabel: "Audit Firm",
    section: "Audit Desk",
    businessTypes: ["audit_firm"],
  },
  {
    id: "FIRM_ANALYTICS",
    label: "Firm Analytics",
    route: "/dashboard/firm/analytics",
    business: "firm",
    businessLabel: "Professional Firm",
    section: "Analytics",
    businessTypes: ["accounting_firm", "audit_firm", "consultancy_firm", "architecture_firm"],
  },
  {
    id: "ECOMMERCE_OVERVIEW",
    label: "Ecommerce Overview",
    route: "/dashboard/ecommerce",
    business: "ecommerce",
    businessLabel: "E-Commerce / Online Store",
    section: "Control Center",
    businessTypes: ["ecommerce"],
  },
  {
    id: "ECOMMERCE_PRODUCTS",
    label: "Product Listings",
    route: "/dashboard/ecommerce/products",
    business: "ecommerce",
    businessLabel: "E-Commerce / Online Store",
    section: "Catalog",
    businessTypes: ["ecommerce"],
  },
  {
    id: "ECOMMERCE_ORDERS",
    label: "Orders",
    route: "/dashboard/ecommerce/orders",
    business: "ecommerce",
    businessLabel: "E-Commerce / Online Store",
    section: "Commercial",
    businessTypes: ["ecommerce"],
  },
  {
    id: "ECOMMERCE_RETURNS",
    label: "Returns",
    route: "/dashboard/ecommerce/returns",
    business: "ecommerce",
    businessLabel: "E-Commerce / Online Store",
    section: "Customer Care",
    businessTypes: ["ecommerce"],
  },
  {
    id: "ECOMMERCE_SHIPPING",
    label: "Shipping",
    route: "/dashboard/ecommerce/shipping",
    business: "ecommerce",
    businessLabel: "E-Commerce / Online Store",
    section: "Fulfillment",
    businessTypes: ["ecommerce"],
  },
  {
    id: "ECOMMERCE_ANALYTICS",
    label: "Ecommerce Analytics",
    route: "/dashboard/ecommerce/analytics",
    business: "ecommerce",
    businessLabel: "E-Commerce / Online Store",
    section: "Control Center",
    businessTypes: ["ecommerce"],
  },
  {
    id: "TRADE_OVERVIEW",
    label: "Import / Export Overview",
    route: "/dashboard/trade",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Control Center",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRADE_SHIPMENTS",
    label: "Shipments",
    route: "/dashboard/trade/shipments",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Operations",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRADE_LC",
    label: "LC / TT",
    route: "/dashboard/trade/lc",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Finance Desk",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRADE_CUSTOMS",
    label: "Customs",
    route: "/dashboard/trade/customs",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Operations",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRADE_IMPORT_COSTING",
    label: "Import Costing",
    route: "/dashboard/trade/costing",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Costing & Compliance",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRADE_COMMERCIAL_INVOICE",
    label: "Commercial Invoice",
    route: "/dashboard/commercial-invoice",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Export Documentation",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRADE_PACKING_LIST",
    label: "Packing List",
    route: "/dashboard/packing-list",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Export Documentation",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRADE_REBATE",
    label: "Export Rebate / Drawback",
    route: "/dashboard/trade/rebate",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Costing & Compliance",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRADE_ANALYTICS",
    label: "Trade Analytics",
    route: "/dashboard/trade/analytics",
    business: "trade",
    businessLabel: "Import / Export",
    section: "Control Center",
    businessTypes: ["import_company", "export_company", "clearing_forwarding"],
  },
  {
    id: "TRANSPORT_OVERVIEW",
    label: "Transport Overview",
    route: "/dashboard/transport",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Control Center",
    businessTypes: ["transport"],
  },
  {
    id: "TRANSPORT_FLEET",
    label: "Fleet",
    route: "/dashboard/transport/fleet",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Operations",
    businessTypes: ["transport"],
  },
  {
    id: "TRANSPORT_TRIPS",
    label: "Trips",
    route: "/dashboard/transport/trips",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Operations",
    businessTypes: ["transport"],
  },
  {
    id: "TRANSPORT_DISPATCH",
    label: "Dispatch Board",
    route: "/dashboard/transport/dispatch",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Operations",
    businessTypes: ["transport"],
  },
  {
    id: "TRANSPORT_DRIVERS",
    label: "Drivers",
    route: "/dashboard/transport/drivers",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Operations",
    businessTypes: ["transport"],
  },
  {
    id: "TRANSPORT_FUEL",
    label: "Fuel Tracking",
    route: "/dashboard/transport/fuel",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Operations",
    businessTypes: ["transport"],
  },
  {
    id: "TRANSPORT_MAINTENANCE",
    label: "Maintenance",
    route: "/dashboard/transport/maintenance",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Operations",
    businessTypes: ["transport"],
  },
  {
    id: "TRANSPORT_EXPENSES",
    label: "Trip Expenses",
    route: "/dashboard/transport/expenses",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Finance Desk",
    businessTypes: ["transport"],
  },
  {
    id: "TRANSPORT_ANALYTICS",
    label: "Transport Analytics",
    route: "/dashboard/transport/analytics",
    business: "transport",
    businessLabel: "Transport / Logistics",
    section: "Control Center",
    businessTypes: ["transport"],
  },
  {
    id: "PHARMACY_OVERVIEW",
    label: "Pharmacy Overview",
    route: "/dashboard/pharmacy",
    business: "pharmacy",
    businessLabel: "Pharmacy / Medical Store",
    section: "Control Center",
    businessTypes: ["pharmacy"],
  },
  {
    id: "PHARMACY_INVENTORY",
    label: "Drug Inventory",
    route: "/dashboard/pharmacy/inventory",
    business: "pharmacy",
    businessLabel: "Pharmacy / Medical Store",
    section: "Inventory",
    businessTypes: ["pharmacy"],
  },
  {
    id: "PHARMACY_BATCHES",
    label: "Batch Control",
    route: "/dashboard/pharmacy/batches",
    business: "pharmacy",
    businessLabel: "Pharmacy / Medical Store",
    section: "Inventory",
    businessTypes: ["pharmacy"],
  },
  {
    id: "PHARMACY_EXPIRY",
    label: "Expiry Tracking",
    route: "/dashboard/pharmacy/expiry",
    business: "pharmacy",
    businessLabel: "Pharmacy / Medical Store",
    section: "Inventory",
    businessTypes: ["pharmacy"],
  },
  {
    id: "PHARMACY_PURCHASES",
    label: "Medicine Purchases",
    route: "/dashboard/pharmacy/purchases",
    business: "pharmacy",
    businessLabel: "Pharmacy / Medical Store",
    section: "Commercial",
    businessTypes: ["pharmacy"],
  },
  {
    id: "PHARMACY_PRESCRIPTIONS",
    label: "Prescriptions",
    route: "/dashboard/pharmacy/prescriptions",
    business: "pharmacy",
    businessLabel: "Pharmacy / Medical Store",
    section: "Operations",
    businessTypes: ["pharmacy"],
  },
  {
    id: "PHARMACY_COUNTER_SALES",
    label: "Counter Sales",
    route: "/dashboard/pharmacy/counter-sales",
    business: "pharmacy",
    businessLabel: "Pharmacy / Medical Store",
    section: "Commercial",
    businessTypes: ["pharmacy"],
  },
  {
    id: "PHARMACY_ANALYTICS",
    label: "Pharmacy Analytics",
    route: "/dashboard/pharmacy/analytics",
    business: "pharmacy",
    businessLabel: "Pharmacy / Medical Store",
    section: "Control Center",
    businessTypes: ["pharmacy"],
  },
  {
    id: "HOTEL_OVERVIEW",
    label: "Hotel Overview",
    route: "/dashboard/hotel",
    business: "hotel",
    businessLabel: "Hotel / Guest House",
    section: "Control Center",
    businessTypes: ["hotel"],
  },
  {
    id: "HOTEL_ROOMS",
    label: "Room Booking",
    route: "/dashboard/hotel/rooms",
    business: "hotel",
    businessLabel: "Hotel / Guest House",
    section: "Inventory",
    businessTypes: ["hotel"],
  },
  {
    id: "HOTEL_FRONT_DESK",
    label: "Front Desk",
    route: "/dashboard/hotel/front-desk",
    business: "hotel",
    businessLabel: "Hotel / Guest House",
    section: "Operations",
    businessTypes: ["hotel"],
  },
  {
    id: "HOTEL_HOUSEKEEPING",
    label: "Housekeeping",
    route: "/dashboard/hotel/housekeeping",
    business: "hotel",
    businessLabel: "Hotel / Guest House",
    section: "Operations",
    businessTypes: ["hotel"],
  },
  {
    id: "HOTEL_ROOM_SERVICE",
    label: "Room Service",
    route: "/dashboard/hotel/room-service",
    business: "hotel",
    businessLabel: "Hotel / Guest House",
    section: "Operations",
    businessTypes: ["hotel"],
  },
  {
    id: "HOTEL_FOLIOS",
    label: "Billing Folios",
    route: "/dashboard/hotel/folios",
    business: "hotel",
    businessLabel: "Hotel / Guest House",
    section: "Commercial",
    businessTypes: ["hotel"],
  },
  {
    id: "HOTEL_GUEST_HISTORY",
    label: "Guest History",
    route: "/dashboard/hotel/guest-history",
    business: "hotel",
    businessLabel: "Hotel / Guest House",
    section: "Commercial",
    businessTypes: ["hotel"],
  },
  {
    id: "HOTEL_ANALYTICS",
    label: "Hotel Analytics",
    route: "/dashboard/hotel/analytics",
    business: "hotel",
    businessLabel: "Hotel / Guest House",
    section: "Control Center",
    businessTypes: ["hotel"],
  },
  {
    id: "SCHOOL_OVERVIEW",
    label: "School Overview",
    route: "/dashboard/school",
    business: "school",
    businessLabel: "School / Academy",
    section: "Control Center",
    businessTypes: ["school"],
  },
  {
    id: "SCHOOL_STUDENTS",
    label: "Students",
    route: "/dashboard/school/students",
    business: "school",
    businessLabel: "School / Academy",
    section: "Academic Desk",
    businessTypes: ["school"],
  },
  {
    id: "SCHOOL_ADMISSIONS",
    label: "Admissions",
    route: "/dashboard/school/admissions",
    business: "school",
    businessLabel: "School / Academy",
    section: "Front Desk",
    businessTypes: ["school"],
  },
  {
    id: "SCHOOL_ATTENDANCE",
    label: "Attendance",
    route: "/dashboard/school/attendance",
    business: "school",
    businessLabel: "School / Academy",
    section: "Academic Desk",
    businessTypes: ["school"],
  },
  {
    id: "SCHOOL_TEACHERS",
    label: "Teachers & Rooms",
    route: "/dashboard/school/teachers",
    business: "school",
    businessLabel: "School / Academy",
    section: "Academic Desk",
    businessTypes: ["school"],
  },
  {
    id: "SCHOOL_FEES",
    label: "Fee Collection",
    route: "/dashboard/school/fees",
    business: "school",
    businessLabel: "School / Academy",
    section: "Finance Desk",
    businessTypes: ["school"],
  },
  {
    id: "SCHOOL_SCHEDULE",
    label: "Class Schedule",
    route: "/dashboard/school/schedule",
    business: "school",
    businessLabel: "School / Academy",
    section: "Academic Desk",
    businessTypes: ["school"],
  },
  {
    id: "SCHOOL_EXAMS",
    label: "Exam Results",
    route: "/dashboard/school/exams",
    business: "school",
    businessLabel: "School / Academy",
    section: "Academic Desk",
    businessTypes: ["school"],
  },
  {
    id: "SCHOOL_ANALYTICS",
    label: "School Analytics",
    route: "/dashboard/school/analytics",
    business: "school",
    businessLabel: "School / Academy",
    section: "Control Center",
    businessTypes: ["school"],
  },
  {
    id: "CONSTRUCTION_OVERVIEW",
    label: "Construction Overview",
    route: "/dashboard/construction",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Control Center",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_PROJECTS",
    label: "Projects",
    route: "/dashboard/construction/projects",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Execution",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_SITES",
    label: "Site Management",
    route: "/dashboard/construction/sites",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Execution",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_MATERIALS",
    label: "Material Control",
    route: "/dashboard/construction/materials",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Procurement",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_BOQ",
    label: "BOQ Control",
    route: "/dashboard/construction/boq",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Commercial",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_BILLING",
    label: "Progress Billing",
    route: "/dashboard/construction/billing",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Commercial",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_EXPENSES",
    label: "Site Expenses",
    route: "/dashboard/construction/expenses",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Commercial",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_CONTRACTOR_PAYMENTS",
    label: "Contractor Payments",
    route: "/dashboard/construction/contractor-payments",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Commercial",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_SUBCONTRACTORS",
    label: "Subcontractors",
    route: "/dashboard/construction/subcontractors",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Execution",
    businessTypes: ["construction"],
  },
  {
    id: "CONSTRUCTION_ANALYTICS",
    label: "Construction Analytics",
    route: "/dashboard/construction/analytics",
    business: "construction",
    businessLabel: "Construction / Contractor",
    section: "Control Center",
    businessTypes: ["construction"],
  },
  {
    id: "REAL_ESTATE_OVERVIEW",
    label: "Real Estate Overview",
    route: "/dashboard/real-estate",
    business: "real_estate",
    businessLabel: "Real Estate",
    section: "Control Center",
    businessTypes: ["real_estate"],
  },
  {
    id: "REAL_ESTATE_PROPERTIES",
    label: "Properties",
    route: "/dashboard/real-estate/properties",
    business: "real_estate",
    businessLabel: "Real Estate",
    section: "Portfolio",
    businessTypes: ["real_estate"],
  },
  {
    id: "REAL_ESTATE_TENANTS",
    label: "Tenants",
    route: "/dashboard/real-estate/tenants",
    business: "real_estate",
    businessLabel: "Real Estate",
    section: "Portfolio",
    businessTypes: ["real_estate"],
  },
  {
    id: "REAL_ESTATE_RENT",
    label: "Rent Collection",
    route: "/dashboard/real-estate/rent",
    business: "real_estate",
    businessLabel: "Real Estate",
    section: "Portfolio",
    businessTypes: ["real_estate"],
  },
  {
    id: "REAL_ESTATE_LEASES",
    label: "Lease Agreements",
    route: "/dashboard/real-estate/leases",
    business: "real_estate",
    businessLabel: "Real Estate",
    section: "Portfolio",
    businessTypes: ["real_estate"],
  },
  {
    id: "REAL_ESTATE_ANALYTICS",
    label: "Real Estate Analytics",
    route: "/dashboard/real-estate/analytics",
    business: "real_estate",
    businessLabel: "Real Estate",
    section: "Control Center",
    businessTypes: ["real_estate"],
  },
  {
    id: "HEALTHCARE_OVERVIEW",
    label: "Healthcare Overview",
    route: "/dashboard/hospital",
    business: "healthcare",
    businessLabel: "Healthcare / Clinic",
    section: "Control Center",
    businessTypes: ["hospital", "clinic"],
  },
  {
    id: "HEALTHCARE_PATIENTS",
    label: "Patient Records",
    route: "/dashboard/hospital/patients",
    business: "healthcare",
    businessLabel: "Healthcare / Clinic",
    section: "Clinical Desk",
    businessTypes: ["hospital", "clinic"],
  },
  {
    id: "HEALTHCARE_APPOINTMENTS",
    label: "Appointments",
    route: "/dashboard/hospital/appointments",
    business: "healthcare",
    businessLabel: "Healthcare / Clinic",
    section: "Front Desk",
    businessTypes: ["hospital", "clinic"],
  },
  {
    id: "HEALTHCARE_PRESCRIPTIONS",
    label: "Prescriptions",
    route: "/dashboard/hospital/prescriptions",
    business: "healthcare",
    businessLabel: "Healthcare / Clinic",
    section: "Clinical Desk",
    businessTypes: ["hospital", "clinic"],
  },
  {
    id: "HEALTHCARE_LAB",
    label: "Lab Tests",
    route: "/dashboard/hospital/lab",
    business: "healthcare",
    businessLabel: "Healthcare / Clinic",
    section: "Clinical Desk",
    businessTypes: ["hospital", "clinic"],
  },
  {
    id: "HEALTHCARE_ANALYTICS",
    label: "Healthcare Analytics",
    route: "/dashboard/hospital/analytics",
    business: "healthcare",
    businessLabel: "Healthcare / Clinic",
    section: "Control Center",
    businessTypes: ["hospital", "clinic"],
  },
  {
    id: "RESTAURANT_OVERVIEW",
    label: "Restaurant Overview",
    route: "/dashboard/restaurant",
    business: "restaurant",
    businessLabel: "Restaurant / Cafe",
    section: "Control Center",
  },
  {
    id: "RESTAURANT_ORDER_BOARD",
    label: "Order Board",
    route: "/dashboard/restaurant/orders",
    business: "restaurant",
    businessLabel: "Restaurant / Cafe",
    section: "Operations",
  },
  {
    id: "RESTAURANT_RESERVATIONS",
    label: "Reservations",
    route: "/dashboard/restaurant/reservations",
    business: "restaurant",
    businessLabel: "Restaurant / Cafe",
    section: "Front Desk",
  },
  {
    id: "RESTAURANT_TABLES",
    label: "Table Management",
    route: "/dashboard/restaurant/tables",
    business: "restaurant",
    businessLabel: "Restaurant / Cafe",
    section: "Front Desk",
  },
  {
    id: "RESTAURANT_MENU",
    label: "Menu Items",
    route: "/dashboard/restaurant/menu",
    business: "restaurant",
    businessLabel: "Restaurant / Cafe",
    section: "Menu & Costing",
  },
  {
    id: "RESTAURANT_KITCHEN",
    label: "Kitchen Orders",
    route: "/dashboard/restaurant/kitchen",
    business: "restaurant",
    businessLabel: "Restaurant / Cafe",
    section: "Operations",
  },
  {
    id: "RESTAURANT_RECIPE_COSTING",
    label: "Recipe Costing",
    route: "/dashboard/restaurant/recipe-costing",
    business: "restaurant",
    businessLabel: "Restaurant / Cafe",
    section: "Menu & Costing",
  },
  {
    id: "RESTAURANT_ANALYTICS",
    label: "Restaurant Analytics",
    route: "/dashboard/restaurant/analytics",
    business: "restaurant",
    businessLabel: "Restaurant / Cafe",
    section: "Control Center",
  },
  {
    id: "SERVICE_OVERVIEW",
    label: "Service Overview",
    route: "/dashboard/services",
    business: "service",
    businessLabel: "Service / Agency",
    section: "Control Center",
  },
  {
    id: "SERVICE_CATALOG",
    label: "Service Catalog",
    route: "/dashboard/services/catalog",
    business: "service",
    businessLabel: "Service / Agency",
    section: "Commercial",
  },
  {
    id: "SERVICE_PROJECTS",
    label: "Client Projects",
    route: "/dashboard/services/projects",
    business: "service",
    businessLabel: "Service / Agency",
    section: "Delivery",
  },
  {
    id: "SERVICE_DELIVERY",
    label: "Delivery Tracker",
    route: "/dashboard/services/delivery",
    business: "service",
    businessLabel: "Service / Agency",
    section: "Delivery",
  },
  {
    id: "SERVICE_TIME_BILLING",
    label: "Time Billing",
    route: "/dashboard/services/time-billing",
    business: "service",
    businessLabel: "Service / Agency",
    section: "Billing",
  },
  {
    id: "FOOD_PROCESSING_OVERVIEW",
    label: "Food Processing Overview",
    route: "/dashboard/food-processing",
    business: "manufacturing",
    businessLabel: "Food Processing",
    section: "Control Center",
    businessTypes: ["food_processing"],
  },
  {
    id: "FOOD_PROCESSING_RECIPE",
    label: "Recipe Costing",
    route: "/dashboard/food-processing/recipe-costing",
    business: "manufacturing",
    businessLabel: "Food Processing",
    section: "Recipe & Costing",
    businessTypes: ["food_processing"],
  },
  {
    id: "FOOD_PROCESSING_ANALYTICS",
    label: "Food Processing Analytics",
    route: "/dashboard/food-processing/analytics",
    business: "manufacturing",
    businessLabel: "Food Processing",
    section: "Control Center",
    businessTypes: ["food_processing"],
  },
  {
    id: "MANUFACTURING_OVERVIEW",
    label: "Manufacturing Overview",
    route: "/dashboard/manufacturing",
    business: "manufacturing",
    businessLabel: "Manufacturing",
    section: "Control Center",
  },
  {
    id: "MANUFACTURING_BOM",
    label: "Bill of Materials",
    route: "/dashboard/manufacturing/bom",
    business: "manufacturing",
    businessLabel: "Manufacturing",
    section: "Production Planning",
  },
  {
    id: "MANUFACTURING_PRODUCTION_ORDERS",
    label: "Production Orders",
    route: "/dashboard/manufacturing/production-orders",
    business: "manufacturing",
    businessLabel: "Manufacturing",
    section: "Production Planning",
  },
  {
    id: "MANUFACTURING_WORK_ORDERS",
    label: "Work Orders",
    route: "/dashboard/manufacturing/work-orders",
    business: "manufacturing",
    businessLabel: "Manufacturing",
    section: "Production Planning",
  },
  {
    id: "MANUFACTURING_RAW_MATERIALS",
    label: "Raw Materials",
    route: "/dashboard/manufacturing/raw-materials",
    business: "manufacturing",
    businessLabel: "Manufacturing",
    section: "Inventory & Quality",
  },
  {
    id: "MANUFACTURING_FINISHED_GOODS",
    label: "Finished Goods",
    route: "/dashboard/manufacturing/finished-goods",
    business: "manufacturing",
    businessLabel: "Manufacturing",
    section: "Inventory & Quality",
  },
  {
    id: "MANUFACTURING_QUALITY",
    label: "Quality Control",
    route: "/dashboard/manufacturing/quality",
    business: "manufacturing",
    businessLabel: "Manufacturing",
    section: "Inventory & Quality",
  },
  {
    id: "RETAIL_POS",
    label: "POS Terminal",
    route: "/dashboard/retail/pos",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Point of Sale",
  },
  {
    id: "RETAIL_POS_SESSIONS",
    label: "POS Sessions",
    route: "/dashboard/retail/pos-sessions",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Point of Sale",
  },
  {
    id: "RETAIL_DISCOUNTS",
    label: "Discounts & Promotions",
    route: "/dashboard/retail/discounts",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Point of Sale",
  },
  {
    id: "RETAIL_LOYALTY",
    label: "Loyalty Points",
    route: "/dashboard/retail/loyalty",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Point of Sale",
  },
  {
    id: "RETAIL_STOCK_TRANSFER",
    label: "Stock Transfer",
    route: "/dashboard/retail/stock-transfer",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Inventory & Multi-Store",
  },
  {
    id: "RETAIL_ONLINE_SYNC",
    label: "Online Store Sync",
    route: "/dashboard/retail/online-sync",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Point of Sale",
  },
  {
    id: "RETAIL_SUPPLIER_PORTAL",
    label: "Supplier Portal",
    route: "/dashboard/retail/supplier-portal",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Point of Sale",
  },
  {
    id: "RETAIL_CATALOG",
    label: "Product Catalog",
    route: "/dashboard/retail/catalog",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Inventory & Multi-Store",
  },
  {
    id: "RETAIL_STOCK_ADJUSTMENT",
    label: "Stock Adjustment",
    route: "/dashboard/retail/stock-adjustment",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Inventory & Multi-Store",
  },
  {
    id: "RETAIL_BATCH_EXPIRY",
    label: "Batch & Expiry",
    route: "/dashboard/retail/batch-expiry",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Inventory & Multi-Store",
  },
  {
    id: "RETAIL_CUSTOMERS",
    label: "Customer List",
    route: "/dashboard/retail/customers",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Customers & Suppliers",
  },
  {
    id: "RETAIL_SUPPLIERS",
    label: "Supplier List",
    route: "/dashboard/retail/suppliers",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Customers & Suppliers",
  },
  {
    id: "RETAIL_BRANCHES",
    label: "Branches",
    route: "/dashboard/retail/branches",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Inventory & Multi-Store",
  },
  {
    id: "RETAIL_BRANCH_USERS",
    label: "Branch Users",
    route: "/dashboard/retail/branch-users",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Inventory & Multi-Store",
  },
  {
    id: "RETAIL_BRANCH_REPORTS",
    label: "Branch Reports",
    route: "/dashboard/retail/branch-reports",
    business: "retail",
    businessLabel: "Retail Store",
    section: "Inventory & Multi-Store",
  },
  {
    id: "DISTRIBUTION_ROUTES",
    label: "Routes",
    route: "/dashboard/distribution/routes",
    business: "distribution",
    businessLabel: "Distribution",
    section: "Operations",
  },
  {
    id: "DISTRIBUTION_DELIVERY",
    label: "Delivery Tracking",
    route: "/dashboard/distribution/delivery",
    business: "distribution",
    businessLabel: "Distribution",
    section: "Operations",
  },
  {
    id: "DISTRIBUTION_VAN_SALES",
    label: "Van Sales",
    route: "/dashboard/distribution/van-sales",
    business: "distribution",
    businessLabel: "Distribution",
    section: "Operations",
  },
  {
    id: "DISTRIBUTION_STOCK_ON_VAN",
    label: "Stock On Van",
    route: "/dashboard/distribution/stock-on-van",
    business: "distribution",
    businessLabel: "Distribution",
    section: "Operations",
  },
  {
    id: "DISTRIBUTION_COLLECTIONS",
    label: "Collections",
    route: "/dashboard/distribution/collections",
    business: "distribution",
    businessLabel: "Distribution",
    section: "Operations",
  },
  {
    id: "DISTRIBUTION_ANALYTICS",
    label: "Analytics",
    route: "/dashboard/distribution/analytics",
    business: "distribution",
    businessLabel: "Distribution",
    section: "Control Center",
  },
  {
    id: "DISTRIBUTION_TRIP_SHEET",
    label: "Trip Sheet",
    route: "/dashboard/distribution/trip-sheet",
    business: "distribution",
    businessLabel: "Distribution",
    section: "Control Center",
  },
  {
    id: "TRADING_OVERVIEW",
    label: "Trading Overview",
    route: "/dashboard/trading",
    business: "trading",
    businessLabel: "Trading",
    section: "Control Center",
  },
  {
    id: "TRADING_ORDER_DESK",
    label: "Order Desk",
    route: "/dashboard/trading/order-desk",
    business: "trading",
    businessLabel: "Trading",
    section: "Control Center",
  },
  {
    id: "TRADING_PROCUREMENT",
    label: "Procurement",
    route: "/dashboard/trading/procurement",
    business: "trading",
    businessLabel: "Trading",
    section: "Control Center",
  },
  {
    id: "TRADING_STOCK_CONTROL",
    label: "Stock Control",
    route: "/dashboard/trading/stock-control",
    business: "trading",
    businessLabel: "Trading",
    section: "Control Center",
  },
  {
    id: "TRADING_OUTSTANDINGS",
    label: "Outstandings",
    route: "/dashboard/trading/outstandings",
    business: "trading",
    businessLabel: "Trading",
    section: "Control Center",
  },
  {
    id: "TRADING_DISPATCH_BOARD",
    label: "Dispatch Board",
    route: "/dashboard/trading/dispatch-board",
    business: "trading",
    businessLabel: "Trading",
    section: "Control Center",
  },
  {
    id: "TRADING_CONVERSION_CENTER",
    label: "Conversion Center",
    route: "/dashboard/trading/conversion-center",
    business: "trading",
    businessLabel: "Trading",
    section: "Control Center",
  },
  {
    id: "TRADING_ANALYTICS",
    label: "Trading Analytics",
    route: "/dashboard/trading/analytics",
    business: "trading",
    businessLabel: "Trading",
    section: "Control Center",
  },
];

export const DASHBOARD_FEATURE_IDS = DASHBOARD_FEATURE_DEFS.map((feature) => feature.id);

export function createDefaultDashboardFeatureFlags(): Record<DashboardFeaturePlanCode, string[]> {
  return {
    STARTER: [...DASHBOARD_FEATURE_IDS],
    PRO: [...DASHBOARD_FEATURE_IDS],
    ENTERPRISE: [...DASHBOARD_FEATURE_IDS],
    CUSTOM: [...DASHBOARD_FEATURE_IDS],
  };
}

export function findDashboardFeatureByRoute(pathname: string): DashboardFeatureDefinition | null {
  const normalized = String(pathname || "").replace(/\/+$/, "") || "/";
  return DASHBOARD_FEATURE_DEFS.find((feature) => {
    const route = feature.route.replace(/\/+$/, "") || "/";
    return normalized === route || normalized.startsWith(`${route}/`);
  }) || null;
}
