// PDF Export Utility
// Note: For production, use a proper PDF library like jsPDF or pdfkit

export function exportToPDF(data: Any[], filename: string, columns: string[]) {
  // Simple HTML-based PDF generation
  // For production, use jsPDF or server-side PDF generation

  const htmlContent = generatePDFHTML(data, columns, filename);

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  }
}

function generatePDFHTML(data: Any[], columns: string[], title: string): string {
  const tableRows = data
    .map(
      (row) => `
    <tr>
      ${columns
        .map((col) => `<td style="border: 1px solid #ddd; padding: 8px;">${row[col] || ""}</td>`)
        .join("")}
    </tr>
  `
    )
    .join("");

  const tableHeaders = columns
    .map((col) => `<th style="border: 1px solid #ddd; padding: 8px; background: #f2f2f2;">${col}</th>`)
    .join("");

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          @media print {
            @page { margin: 1cm; }
            body { margin: 0; }
          }
          body {
            font-family: Arial, sans-serif;
            padding: 20px;
          }
          h1 {
            text-align: center;
            margin-bottom: 20px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
          }
          th {
            background-color: #f2f2f2;
            font-weight: bold;
          }
          .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #666;
          }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p style="text-align: right; margin-bottom: 20px;">
          Generated: ${new Date().toLocaleString()}
        </p>
        <table>
          <thead>
            <tr>${tableHeaders}</tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>
        <div class="footer">
          <p>Generated by Smart Business Accounts System</p>
        </div>
      </body>
    </html>
  `;
}

// Alternative: Use jsPDF for better PDF generation
export async function exportToPDFAdvanced(
  data: Any[],
  filename: string,
  columns: { header: string; dataKey: string; width?: number }[]
) {
  try {
    // Dynamic import of jsPDF (install: npm install jspdf)
    const { default: jsPDF } = await import("jspdf");
    const autoTable = (await import("jspdf-autotable")).default;

    const doc = new jsPDF();
    
    doc.text(filename, 14, 20);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);

    autoTable(doc, {
      head: [columns.map((c) => c.header)],
      body: data.map((row) =>
        columns.map((col) => row[col.dataKey] || "")
      ),
      startY: 40,
      styles: { fontSize: 8 },
      columnStyles: columns.reduce((acc: Any, col, idx) => {
        if (col.width) acc[idx] = { cellWidth: col.width };
        return acc;
      }, {}),
    });

    doc.save(`${filename}.pdf`);
  } catch (error) {
    console.error("PDF export error:", error);
    // Fallback to HTML print
    exportToPDF(data, filename, columns.map((c) => c.header));
  }
}
