export const PERMISSIONS = {

  // Admin
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_LOGS: "VIEW_LOGS",

  // Forms

  // Accounts

  VIEW_ACCOUNTS: "VIEW_ACCOUNTS",

  CREATE_CPV: "CREATE_CPV",
  CREATE_CRV: "CREATE_CRV",

  // Catalog

  VIEW_CATALOG: "VIEW_CATALOG",

  CREATE_ACCOUNTS: "CREATE_ACCOUNTS",
  CREATE_ITEMS: "CREATE_ITEMS",
  CREATE_STOCK_RATE: "CREATE_STOCK_RATE",

  VIEW_ACCOUNTING: "VIEW_ACCOUNTING",

  // Sales & Distribution
  CREATE_QUOTATION: "CREATE_QUOTATION",
  CREATE_DELIVERY_CHALLAN: "CREATE_DELIVERY_CHALLAN",

  // Inventory

  VIEW_INVENTORY: "VIEW_INVENTORY",

  CREATE_PURCHASE_ORDER: "CREATE_PURCHASE_ORDER",
  CREATE_PURCHASE_INVOICE: "CREATE_PURCHASE_INVOICE",
  CREATE_SALES_INVOICE: "CREATE_SALES_INVOICE",
  CREATE_SALE_RETURN: "CREATE_SALE_RETURN",
  CREATE_OUTWARD: "CREATE_OUTWARD",

  // Reports
  //Financial Reports

  VIEW_FINANCIAL_REPORTS: "VIEW_FINANCIAL_REPORTS",
  VIEW_REPORTS: "VIEW_REPORTS", // General reports permission

  VIEW_AGEING_REPORT: "VIEW_AGEING_REPORT",
  VIEW_LEDGER_REPORT: "VIEW_LEDGER_REPORT",
  VIEW_TRIAL_BALANCE_REPORT: "VIEW_TRIAL_BALANCE_REPORT",
  VIEW_PROFIT_LOSS_REPORT: "VIEW_PROFIT_LOSS_REPORT",
  VIEW_BALANCE_SHEET_REPORT: "VIEW_BALANCE_SHEET_REPORT",

  //Inventory Reports

  VIEW_INVENTORY_REPORTS: "VIEW_INVENTORY_REPORTS",


  VIEW_INWARD: "VIEW_INWARD",
  VIEW_OUTWARD: "VIEW_OUTWARD",
  VIEW_SALES_REPORT: "VIEW_SALES_REPORT",
  VIEW_STOCK_LEDGER: "VIEW_STOCK_LEDGER",
  VIEW_STOCK_SUMMARY: "VIEW_STOCK_SUMMARY",
  VIEW_LOW_STOCK: "VIEW_LOW_STOCK",
  VIEW_LOCATION: "VIEW_LOCATION",

  // Admin Management
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_ROLES: "MANAGE_ROLES",
  VIEW_AUDIT_LOG: "VIEW_AUDIT_LOG",

  // Phase 1: Banking & Payment
  BANK_RECONCILIATION: "BANK_RECONCILIATION",
  PAYMENT_RECEIPTS: "PAYMENT_RECEIPTS",
  EXPENSE_VOUCHERS: "EXPENSE_VOUCHERS",
  TAX_CONFIGURATION: "TAX_CONFIGURATION",

  // HR & Payroll
  VIEW_HR_PAYROLL: "VIEW_HR_PAYROLL",

  // CRM
  VIEW_CRM: "VIEW_CRM",

  // Settings
  VIEW_SETTINGS: "VIEW_SETTINGS",

  // Advanced Features
  BUDGET_PLANNING: "BUDGET_PLANNING",
  RECURRING_TRANSACTIONS: "RECURRING_TRANSACTIONS",
  FINANCIAL_YEAR: "FINANCIAL_YEAR",
  BACKUP_RESTORE: "BACKUP_RESTORE",
  EMAIL_SETTINGS: "EMAIL_SETTINGS",


} as const;
