/**
 * Regenerates the light-theme values for the variables scripts/theme-codemod.cjs
 * writes into the source (--dk-*, --dkb-*, --dkr-*, --tx-*, --txr-*, --ta-*).
 *
 * Scans app/ and components/ for every such variable in use and rewrites the
 * block between the THEME-VARS markers in app/globals.css. Run it after the
 * codemod, or after adding a new literal colour by hand in the same form.
 *
 * Usage: node scripts/theme-vars.cjs
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const CSS = path.join(ROOT, "app/globals.css");
const START = "/* THEME-VARS:START (generated by scripts/theme-vars.cjs — do not edit by hand) */";
const END = "/* THEME-VARS:END */";

function walk(dir, out) {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) { if (ent.name !== "node_modules") walk(p, out); }
    else if (/\.tsx?$/.test(ent.name)) out.push(p);
  }
  return out;
}

const names = { dk: new Set(), dkb: new Set(), dkr: new Set(), tx: new Set(), txr: new Set(), ta: new Set() };
for (const f of [...walk(path.join(ROOT, "app"), []), ...walk(path.join(ROOT, "components"), [])]) {
  const src = fs.readFileSync(f, "utf8");
  for (const m of src.matchAll(/var\(--(dk|dkb|dkr|tx|txr)-([0-9a-f]{6})\b/g)) names[m[1]].add(m[2]);
  for (const m of src.matchAll(/var\(--ta-(\d{2})\b/g)) names.ta.add(m[1]);
}

const rgbOf = (h) => [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
function lum([r, g, b]) {
  const f = (v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
}
function toHsl([r, g, b]) {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b), l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min, s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  const h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return [h / 6, s, l];
}
function fromHsl([h, s, l]) {
  if (s === 0) return [l, l, l].map((v) => Math.round(v * 255));
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s, p = 2 * l - q;
  const t = (x) => { if (x < 0) x += 1; if (x > 1) x -= 1; return x < 1 / 6 ? p + (q - p) * 6 * x : x < 1 / 2 ? q : x < 2 / 3 ? p + (q - p) * (2 / 3 - x) * 6 : p; };
  return [t(h + 1 / 3), t(h), t(h - 1 / 3)].map((v) => Math.round(v * 255));
}
// Same hue, dark enough to read on white (4.5:1). Pale neutrals (text that was
// light-grey on dark) are mirrored: the palest become near-black.
function forWhite(h) {
  const rgb0 = rgbOf(h);
  let [hh, s, l] = toHsl(rgb0);
  // Chroma, not HSL saturation: #f1f5f9 has s≈0.4 but is plainly grey.
  const chroma = (Math.max(...rgb0) - Math.min(...rgb0)) / 255;
  if (chroma < 0.12) { l = Math.min(0.42, Math.max(0.1, 1 - l)); s = Math.min(s, 0.2); }
  else { l = Math.min(l, 0.45); s = Math.min(s, 0.65); } // deep shades are less saturated
  let rgb = fromHsl([hh, s, l]);
  while (1.05 / (lum(rgb) + 0.05) < 4.5 && l > 0.05) { l -= 0.01; rgb = fromHsl([hh, s, l]); }
  return rgb;
}
const hex = (rgb) => "#" + rgb.map((v) => v.toString(16).padStart(2, "0")).join("");

function rows(list, val) {
  const decls = [...list].sort().map((n) => val(n));
  const out = [];
  for (let i = 0; i < decls.length; i += 3) out.push("  " + decls.slice(i, i + 3).join(" "));
  return out.join("\n");
}

const body = [
  "html:not(.dark) {",
  rows(names.dk, (n) => `--dk-${n}: var(--card-bg);`),
  rows(names.dkb, (n) => `--dkb-${n}: var(--border);`),
  rows(names.dkr, (n) => `--dkr-${n}: 255, 255, 255;`),
  rows(names.tx, (n) => `--tx-${n}: ${hex(forWhite(n))};`),
  rows(names.txr, (n) => `--txr-${n}: ${forWhite(n).join(", ")};`),
  // Text alpha: .3 of near-black on white is ~2:1. Lift every faint alpha into
  // readable range while keeping the ordering (fainter stays fainter).
  rows(names.ta, (n) => `--ta-${n}: ${Math.min(1, 0.5 + (+n / 100) * 0.7).toFixed(2)};`),
  "}",
].filter(Boolean).join("\n");

let css = fs.readFileSync(CSS, "utf8");
const block = `${START}\n${body}\n${END}`;
if (css.includes(START)) css = css.slice(0, css.indexOf(START)) + block + css.slice(css.indexOf(END) + END.length);
else throw new Error("THEME-VARS markers not found in app/globals.css");
fs.writeFileSync(CSS, css);
console.log(Object.fromEntries(Object.entries(names).map(([k, v]) => [k, v.size])));
